/**
 * ApexKit Global Types & IntelliSense
 * Auto-generated by apexkit-watch.js
 */

export interface Collections {
  "docs": {
    slug?: string;
    added_by: number | string;
    category: "getting started" | "integrations" | "core concepts" | "community guides" | "others";
    content: string;
    title: string;
  };
  "why_apexkit": {
    color: string;
    order?: number;
    title: string;
    icon?: string;
    description: string;
  };
  "use_cases": {
    icon_string?: string;
    title: string;
    icon: string;
    order?: number;
  };
  "news": {
    headline: string;
    date: string;
    body: string;
    is_featured?: boolean;
  };
  "roadmap": {
    description: string;
    status?: "planned" | "in-progress" | "done";
    quarter?: string;
    progress?: number;
    headline: string;
  };
  "changelog": {
    body: string;
    version?: string;
    is_latest?: boolean;
    release_date?: string;
  };
  "blog": {
    body: string;
    cover_image?: string;
    tags?: Record<string, any> | any[];
    read_time?: string;
    author_id: number | string;
    headline: string;
    subheadline: string;
  };
  "optimizations": {
    slug: string;
    title: string;
    tags?: Record<string, any> | any[];
    upvotes: number;
    content: string;
    downvotes: number;
    author_id: (number | string)[];
  };
  "tenancy_offers": {
    provider_name: string;
    specs: string;
    status: "available" | "full" | "waitlist";
    region: string;
    request_access_link: string;
    description: string;
    available_slots: number;
    provider_id: (number | string)[];
  };
  "sandbox_registry": {
    issue_title: string;
    sandbox_url?: string;
    description?: string;
    sandbox_id: string;
    status: "open" | "closed";
    author_id: (number | string)[];
  };
  "community_threads": {
    title: string;
    type: "discussion" | "issue";
    content: string;
    status?: "open" | "closed" | "in-progress";
    author_id: (number | string)[];
  };
  "hub_content": {
    title?: string;
  };
  "thread_comments": {
    content: string;
    thread_id: (number | string)[];
    author_id: (number | string)[];
  };
  "profiles": {
    user_id: number | string;
    last_name?: string;
    avatar?: string;
    first_name?: string;
    username?: string;
    github_url?: string;
    bio?: string;
  };
  "ecosystem_items": {
    title: string;
    type: "starter" | "showcase" | "script" | "ai_action" | "schema" | "template" | "site";
    file: string;
    url?: string;
    install_command?: string;
    tags?: Record<string, any> | any[];
    description: string;
    author_id: (number | string)[];
  };
  "optimizations_conversations": {
    content: string;
    author_id: (number | string)[];
    optimization_id: (number | string)[];
  };
  "optimizations_votes": {
    type: "up" | "down";
    voter_id: (number | string)[];
    optimization_id: (number | string)[];
  };
  "careers": {
    department: string;
    salary?: string;
    location: string;
    type: string;
    title: string;
    description: string;
    author_id: number | string;
  };
  "jobs": {
    location: string;
    company: string;
    department?: string;
    type: string;
    description: string;
    apply_url: string;
    salary: string;
    title: string;
    author_id: (number | string)[];
  };
  "tenant_registry": {
    app_name: string;
    tenant_id: string;
    usage_or_description?: string;
    owner_id: number | string;
  };
  "posts": {
    content?: string;
    title?: string;
  };
}

export type CollectionName = "docs" | "why_apexkit" | "use_cases" | "news" | "roadmap" | "changelog" | "blog" | "optimizations" | "tenancy_offers" | "sandbox_registry" | "community_threads" | "hub_content" | "thread_comments" | "profiles" | "ecosystem_items" | "optimizations_conversations" | "optimizations_votes" | "careers" | "jobs" | "tenant_registry" | "posts";

export interface CollectionExpands {
  "docs": {
    [reverse_relation: string]: any;
  };
  "why_apexkit": {
    [reverse_relation: string]: any;
  };
  "use_cases": {
    [reverse_relation: string]: any;
  };
  "news": {
    [reverse_relation: string]: any;
  };
  "roadmap": {
    [reverse_relation: string]: any;
  };
  "changelog": {
    [reverse_relation: string]: any;
  };
  "blog": {
    [reverse_relation: string]: any;
  };
  "optimizations": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "tenancy_offers": {
    provider_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "sandbox_registry": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "community_threads": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "hub_content": {
    [reverse_relation: string]: any;
  };
  "thread_comments": {
    thread_id?: Array<{ id: number | string; data: Collections["community_threads"]; created: string; updated: string; expand?: any }>;
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "profiles": {
    [reverse_relation: string]: any;
  };
  "ecosystem_items": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "optimizations_conversations": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    optimization_id?: Array<{ id: number | string; data: Collections["optimizations"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "optimizations_votes": {
    voter_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    optimization_id?: Array<{ id: number | string; data: Collections["optimizations"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "careers": {
    [reverse_relation: string]: any;
  };
  "jobs": {
    author_id?: Array<{ id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "tenant_registry": {
    owner_id?: { id: number | string; data: Collections["profiles"]; created: string; updated: string; expand?: any };
    [reverse_relation: string]: any;
  };
  "posts": {
    [reverse_relation: string]: any;
  };
}



export type TriggerType =
  /** Triggered via HTTP GET/POST/PUT/DELETE on /api/v1/run/:name or /api/v1/webhook/:name */
  | "manual"
  /** Runs before a record is inserted. Can validate or mutate data. */
  | "before_create_record"
  /** Runs after a record is inserted. Used for notifications/indexes. */
  | "after_create_record"
  /** Runs before an existing record is updated. Can validate changes. */
  | "before_update_record"
  /** Runs after a record is updated. */
  | "after_update_record"
  /** Runs before a record is deleted. Can block deletion. */
  | "before_delete_record"
  /** Runs after a record has been deleted. */
  | "after_delete_record"
  /** Intercepts list queries before they execute. */
  | "before_list_records"
  /** Filters or transforms listed records before response. */
  | "after_list_records"
  /** Runs before a single record is fetched. */
  | "before_get_record"
  /** Transforms a fetched record before response. */
  | "after_get_record"
  /** Runs before user authentication. Can verify IP/Rate limits. */
  | "before_user_login"
  /** Runs after successful user login. */
  | "after_user_login"
  /** Runs before user registration. Enforce roles or rules. */
  | "before_user_create"
  /** Runs after user registration. Trigger welcome emails. */
  | "after_user_create"
  /** Runs before a user is deleted. */
  | "before_user_delete"
  /** Runs after a user is deleted. */
  | "after_user_delete"
  /** Intercepts user list queries. */
  | "before_list_users"
  /** Transforms user list responses. */
  | "after_list_users"
  /** Validates collection schema before creation. */
  | "before_collection_create"
  /** Runs after collection creation. */
  | "after_collection_create"
  /** Runs before collection schema updates. */
  | "before_collection_update"
  /** Runs after collection schema updates. */
  | "after_collection_update"
  /** Runs before collection deletion. */
  | "before_collection_delete"
  /** Runs before a file is written to storage. */
  | "before_file_upload"
  /** Runs after file upload. Can trigger virus scan or indexing. */
  | "after_file_upload"
  /** Runs before file is deleted. */
  | "before_file_delete"
  /** Runs after file is deleted. */
  | "after_file_delete"
  /** Runs before relationship is linked. */
  | "before_relation_create"
  /** Runs after relationship is linked. */
  | "after_relation_create"
  /** Runs before relationship is removed. */
  | "before_relation_delete"
  /** Runs after relationship is removed. */
  | "after_relation_delete"
  /** Runs before a tenant database is provisioned. */
  | "before_tenant_create"
  /** Runs after tenant database is provisioned. */
  | "after_tenant_create"
  /** Intercepts all incoming HTTP requests to a tenant. */
  | "before_tenant_request"
  /** Processes tenant HTTP response metrics. */
  | "after_tenant_request"
  /** Intercepts sandbox requests. */
  | "before_sandbox_request"
  /** Processes sandbox response metrics. */
  | "after_sandbox_request"
  /** Intercepts AI Prompt Actions to inject RAG search vectors. */
  | "before_ai_run"
  /** Runs after AI Prompt execution. */
  | "after_ai_run"
  /** Fires when revectorization job begins. */
  | "on_vectorization_start"
  /** Executed periodically according to Cron expression settings. */
  | "cron"
  /** Dynamic Query/Mutation field resolver for GraphQL schema. */
  | "graphql";

export type ScriptType = "webhook" | "custom:module" | "esm:module" | "template" | "ai_action";
export type ScriptVisibility = "private" | "public";

export interface FileMetadata {
  id?: number;
  name?: string;
  extension?: "js" | "ts" | "html" | "json" | string;
  target_collection?: CollectionName | null;
  type?: ScriptType;
  path?: string;
  trigger_type?: TriggerType;
  active?: boolean;
  visibility?: ScriptVisibility;
}

export interface AuthContext {
  id: number | string;
  email: string;
  role: string;
  scope: string;
}

export interface RecordItem<T extends keyof Collections = any> {
  id: number | string;
  data: T extends keyof Collections ? Collections[T] : any;
  created: string;
  updated: string;
  expand?: T extends keyof CollectionExpands ? CollectionExpands[T] : any;
}

export interface RecordHookEvent<T extends keyof Collections = any> {
  trigger: TriggerType;
  record: {
    id: number | string | null;
    data: T extends keyof Collections ? Collections[T] : any;
  };
  collection: {
    id: number;
    name: string;
    schema?: any;
  };
  auth: AuthContext | null;
}

export interface VoidHookEvent {
  trigger: TriggerType;
  data: any;
  auth: AuthContext | null;
  timestamp: string;
}

declare global {
  const __fileMetadata__: FileMetadata;

  /** ApexKit Database Client */
  const $db: {
    records: {
      list<T extends keyof Collections>(
        collection: T,
        options?: {
          page?: number;
          per_page?: number;
          limit?: number;
          offset?: number;
          sort?: string;
          filter?: string | Record<string, any>;
          expand?: string;
          fields?: string;
        }
      ): Promise<{ items: RecordItem<T>[]; total: number }>;

      get<T extends keyof Collections>(
        collection: T,
        id: number | string,
        expand?: string
      ): Promise<RecordItem<T> | null>;

      create<T extends keyof Collections>(
        collection: T,
        data: Partial<Collections[T]>
      ): Promise<{ id: number | string }>;

      update<T extends keyof Collections>(
        collection: T,
        id: number | string,
        data: Partial<Collections[T]>
      ): Promise<RecordItem<T>>;

      delete(collection: string, id: number | string): Promise<boolean>;

      searchVector<T extends keyof Collections>(
        collection: T,
        field: string,
        vector: number[],
        limit?: number
      ): Promise<(RecordItem<T> & { _score: number })[]>;

      getVector(
        collection: string,
        id: number | string
      ): Promise<{ field_name: string; vector: number[]; model: string }[]>;

      instantSearch(
        collection: string,
        query: string,
        limit?: number
      ): Promise<{ id: number | string; score: number; snippet: any }[]>;
    };

    query(queryObject: {
      from: string;
      select?: any[];
      where?: Record<string, any>;
      group_by?: string[];
      sort?: string;
      limit?: number;
      offset?: number;
      system?: boolean;
      pipeline?: any[];
    }): Promise<any[]>;

    users: {
      create(
        email: string,
        passwordHash: string,
        role: string,
        metadata?: Record<string, any>
      ): Promise<{ id: number | string; email: string; role: string }>;
      get(email: string): Promise<{ id: number | string; email: string; role: string; metadata?: any } | null>;
    };

    collections: {
      list(): Promise<{ id: number; name: string; schema?: any; index?: string }[]>;
    };

    files: {
      list(
        limit?: number,
        offset?: number
      ): Promise<
        { id: number | string; filename: string; original_name: string; mime_type: string; size: number; created_at: string }[]
      >;
    };
  };

  /** Universal HTTP Client */
  const $http: {
    get(url: string): Promise<string>;
    post(url: string, body: any): Promise<string>;
  };

  /** Native Storage & File Engine */
  const $files: {
    read(filename: string): Promise<string>;
    delete(filenameOrId: string | number): Promise<boolean>;
    save(
      filename: string,
      data: string | ArrayBuffer | Uint8Array,
      mime?: string
    ): Promise<{ id: number | string; url: string; filename: string }>;
    getSignedUrl(filename: string, ttl_secs?: number): Promise<string>;
  };

  /** Scoped Virtual File System */
  const $fs: {
    read(path: string): Promise<string>;
    readBytes(path: string): Promise<string>;
    write(path: string, content: string): Promise<boolean>;
    writeBytes(path: string, data: string | ArrayBuffer | Uint8Array): Promise<boolean>;
    delete(path: string): Promise<boolean>;
    list(path: string): Promise<{ name: string; isDir: boolean; size: number }[]>;
    exists(path: string): Promise<boolean>;
    mkdir(path: string): Promise<boolean>;
    stat(path: string): Promise<{ size: number; isDir: boolean; created?: number; modified?: number }>;
  };

  /** In-Memory & Tenant-Isolated Fast Cache */
  const $cache: {
    get(key: string): Promise<string | null>;
    set(key: string, value: any, ttl_secs?: number): Promise<void>;
    delete(key: string): Promise<void>;
    del(key: string): Promise<void>;
    incr(key: string, delta?: number): Promise<number>;
    listKeys(): Promise<string[]>;
  };

  /** Outbound SMTP Email Dispatcher */
  const $mail: {
    send(to: string, subject: string, body: string): Promise<boolean>;
  };

  /** Real-time WebSocket & SSE Event Dispatcher */
  const $realtime: {
    send(channel: string, event: string, data: any): Promise<boolean>;
  };

  /** Script Inter-calling Engine */
  const $run: {
    script(name: string, payload: any): Promise<any>;
  };

  /** Cryptographic & String Utilities */
  const $util: {
    uuid(): string;
    slugify(text: string): string;
    hash(text: string, alg: "sha256" | "sha512"): string;
    hmac(text: string, key: string): string;
    base64Encode(data: string | ArrayBuffer | Uint8Array): string;
    base64EncodeBuffer(buffer: ArrayBuffer | Uint8Array): string;
    base64Decode(text: string): string;
    base64DecodeBuffer(text: string): ArrayBuffer;
    sleep(ms: number): Promise<void>;
    randomHex(len?: number): string;
  };

  /** Environment & Configuration Secrets Accessor */
  const $env: {
    get(key: string): Promise<string>;
    has(key: string): Promise<boolean>;
    list(): Promise<Record<string, string>>;
    readonly BASE_URL: string;
    readonly APP_URL: string;
    readonly LOCAL_BASE_URL: string;
    readonly LOCAL_APP_URL: string;
    readonly SMTP_BLOCKED: boolean;
  };

  function fetch(
    input: string | Request | URL,
    init?: { method?: string; headers?: any; body?: any; redirect?: "follow" | "manual" | "error" }
  ): Promise<Response>;
}
export {};